base: /
baseVariants: {  }
errorHandling: {  }
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ltr
    flag: de
    languageId: '0'
rootPageId: 1
routes: {  }
routeEnhancers:
  Beratungsstellensuche:
    type: Extbase
    extension: bzga_beratungsstellensuche
    plugin: Pi1
    routes:
      -   routePath: '/beratungsstelle/{entry-title}'
          _controller: 'Entry::show'
          _arguments:
            entry-title: entry
    defaultController: 'Entry::list'
    defaults:
      page: '0'
    aspects:
      page:
        type: StaticRangeMapper
        start: '1'
        end: '1000'
      entry-title:
        type: PersistedAliasMapper
        tableName: tx_bzgaberatungsstellensuche_domain_model_entry
        routeFieldName: slug

