# GlobalSettings.yml

---
conf.py:

  project: Project Name
  copyright: 1970-2099
  version: 0.0
  release: 0.0.0

  highlight_language: none
  html_theme: t3org
  pygments_style: friendly
  today_fmt: '%Y-%m-%d %H:%M'

  latex_documents: []
  latex_elements: {}

  latex_documents_EXAMPLE:
  - - Index
    - extension-key.tex
    - Title of the manual
    - Name of the author
    - manual

  latex_elements_EXAMPLE:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}

  extensions:
  - sphinx.ext.extlinks
  - sphinx.ext.ifconfig
  - sphinx.ext.intersphinx
  - t3sphinx.ext.t3extras
  - t3sphinx.ext.t3tablerows
  - t3sphinx.ext.targets

  extlinks:
    forge:
    - https://forge.typo3.org/issues/%s
    - 'forge: '

  intersphinx_mapping: {}

  intersphinx_mapping_RECOMMENDED:

    t3api:
    - https://docs.typo3.org/typo3cms/CoreApiReference
    - null

    t3cgl:
    - https://docs.typo3.org/typo3cms/CodingGuidelinesReference
    - null

    t3editors:
    - https://docs.typo3.org/typo3cms/EditorsTutorial
    - null

    t3extbase:
    - https://docs.typo3.org/typo3cms/ExtbaseGuide
    - null

    t3extbasebook:
    - https://docs.typo3.org/typo3cms/ExtbaseFluidBook/
    - null

    t3fal:
    - https://docs.typo3.org/typo3cms/FileAbstractionLayerReference
    - null

    t3start:
    - https://docs.typo3.org/typo3cms/GettingStartedTutorial
    - null

    t3inside:
    - https://docs.typo3.org/typo3cms/InsideTypo3Reference
    - null

    t3install:
    - https://docs.typo3.org/typo3cms/InstallationGuide
    - null

    # t3isr:
    # - https://docs.typo3.org/typo3cms/IndexedSearchReference
    # - null

    t3l10n:
    - https://docs.typo3.org/typo3cms/FrontendLocalizationGuide
    - null

    t3security:
    - https://docs.typo3.org/typo3cms/SecurityGuide
    - null

    t3services:
    - https://docs.typo3.org/typo3cms/Typo3ServicesReference
    - null

    t3skinning:
    - https://docs.typo3.org/typo3cms/SkinningReference/
    - null

    t3tca:
    - https://docs.typo3.org/typo3cms/TCAReference
    - null

    t3templating:
    - https://docs.typo3.org/typo3cms/TemplatingTutorial/
    - null

    t3ts45:
    - https://docs.typo3.org/typo3cms/TyposcriptIn45MinutesTutorial
    - null

    t3tsconfig:
    - https://docs.typo3.org/typo3cms/TSconfigReference
    - null

    t3tsref:
    - https://docs.typo3.org/typo3cms/TyposcriptReference
    - null

    t3tssyntax:
    - https://docs.typo3.org/typo3cms/TyposcriptSyntaxReference
    - null

...
